pipeline {
    agent any

    environment {
        DOCKER_HUB_CREDENTIALS = credentials('dockerhub-credentials')
        DOCKER_IMAGE = "slimzy29/messaging_app-web"
        BRANCH_NAME = "main"
    }

    stages {
        stage('Checkout Code') {
            steps {
                git branch: "${BRANCH_NAME}", 
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/adetuyiTolu/alx-backend-python.git'
            }
        }

        stage('Run in Python Docker') {
            steps {
                sh """
                    docker run --rm -v \$PWD:/app -w /app python:3.11-slim \
                    bash -c "pip install --upgrade pip && pip install -r messaging_app/requirements.txt && pytest --maxfail=1 --disable-warnings -q --junitxml=pytest-report.xml"
                """
            }
        }

        stage('Build Docker Image') {
            steps {
                sh "docker build -t ${DOCKER_IMAGE}:${BUILD_NUMBER} ."
            }
        }

        stage('Push Docker Image') {
            steps {
                sh """
                    echo $DOCKER_HUB_CREDENTIALS_PSW | docker login -u $DOCKER_HUB_CREDENTIALS_USR --password-stdin
                    docker push ${DOCKER_IMAGE}:${BUILD_NUMBER}
                    docker tag ${DOCKER_IMAGE}:${BUILD_NUMBER} ${DOCKER_IMAGE}:latest
                    docker push ${DOCKER_IMAGE}:latest
                """
            }
        }
    }

    post {
        success { echo "✅ Docker image build and push successful!" }
        failure { echo "❌ Build failed. Check logs." }
    }
}
