name: Build and Push Docker Image

on:
  push:
    branches:
      - main   # only build & push when code is merged to main
  workflow_dispatch: # allow manual trigger

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Login to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build Docker Image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/messaging-app:${{ github.sha }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/messaging-app:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/messaging-app:latest

      # Push Docker Image
      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/messaging-app:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USERNAME }}/messaging-app:latest
